# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  system.debug: true
steps:
  - task: NodeTool@0
    inputs:    
      versionSpec: '10.x'
  - script:
      npm install @angular/cli -g
    workingDirectory: 'Client'
  - script:
      npm install
    workingDirectory: 'Client'
  - script:  
      ng build 
    displayName: 'ng build'
    workingDirectory: Client
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'Client/dist'
      ArtifactName: angular2 